#
#  Makefile for the ASM9260 CAN controller drivers.
#

obj-$(CONFIG_CAN_ASM9260) +=asm9260.o
obj-$(CONFIG_CAN0_ASM9260_PLATFORM) += asm9260_platform.o
obj-$(CONFIG_CAN1_ASM9260_PLATFORM) += asm9260_platform.o



ccflags-$(CONFIG_CAN_DEBUG_DEVICES) := -DDEBUG
